backend:
 name: git_gateway
 repo: faciasweb-sketch/pagina-web-facias
 branch: main

media_folder: "Assets"
public_folder: "/Assets"

collections:
  - name: "novedades"
    label: "Novedades Destacadas"
    folder: "datos/novedades"
    create: true
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título de la Novedad", name: "title", widget: "string" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["AMBIENTE", "SALUD", "INSTITUCIONAL"] }
      - { label: "Fecha de Publicación", name: "fecha", widget: "date", format: "DD de MMMM, YYYY" }
      - { label: "Imagen de Portada", name: "imagen", widget: "image" }
      - { label: "Contenido/Cuerpo", name: "body", widget: "text" }
